// Capitale de chaque pays (utilisée comme ville par défaut quand on n'a pas de liste plus détaillée).
const CAPITALS: Record<string, string> = {
  'Afghanistan': 'Kaboul',
  'Afrique du Sud': 'Pretoria',
  'Albanie': 'Tirana',
  'Algérie': 'Alger',
  'Allemagne': 'Berlin',
  'Andorre': 'Andorre-la-Vieille',
  'Angola': 'Luanda',
  'Antigua-et-Barbuda': "Saint John's",
  'Arabie saoudite': 'Riyad',
  'Argentine': 'Buenos Aires',
  'Arménie': 'Erevan',
  'Australie': 'Canberra',
  'Autriche': 'Vienne',
  'Azerbaïdjan': 'Bakou',
  'Bahamas': 'Nassau',
  'Bahreïn': 'Manama',
  'Bangladesh': 'Dacca',
  'Barbade': 'Bridgetown',
  'Belgique': 'Bruxelles',
  'Belize': 'Belmopan',
  'Bénin': 'Porto-Novo',
  'Bhoutan': 'Thimphou',
  'Biélorussie': 'Minsk',
  'Birmanie': 'Naypyidaw',
  'Bolivie': 'Sucre',
  'Bosnie-Herzégovine': 'Sarajevo',
  'Botswana': 'Gaborone',
  'Brésil': 'Brasilia',
  'Brunei': 'Bandar Seri Begawan',
  'Bulgarie': 'Sofia',
  'Burkina Faso': 'Ouagadougou',
  'Burundi': 'Gitega',
  'Cambodge': 'Phnom Penh',
  'Cameroun': 'Yaoundé',
  'Canada': 'Ottawa',
  'Cap-Vert': 'Praia',
  'Chili': 'Santiago',
  'Chine': 'Pékin',
  'Chypre': 'Nicosie',
  'Colombie': 'Bogota',
  'Comores': 'Moroni',
  'Congo': 'Brazzaville',
  'Corée du Nord': 'Pyongyang',
  'Corée du Sud': 'Séoul',
  'Costa Rica': 'San José',
  "Côte d'Ivoire": 'Yamoussoukro',
  'Croatie': 'Zagreb',
  'Cuba': 'La Havane',
  'Danemark': 'Copenhague',
  'Djibouti': 'Djibouti',
  'Dominique': 'Roseau',
  'Égypte': 'Le Caire',
  'Émirats arabes unis': 'Abou Dabi',
  'Équateur': 'Quito',
  'Érythrée': 'Asmara',
  'Espagne': 'Madrid',
  'Estonie': 'Tallinn',
  'Eswatini': 'Mbabane',
  'États-Unis': 'Washington',
  'Éthiopie': 'Addis-Abeba',
  'Fidji': 'Suva',
  'Finlande': 'Helsinki',
  'France': 'Paris',
  'Gabon': 'Libreville',
  'Gambie': 'Banjul',
  'Géorgie': 'Tbilissi',
  'Ghana': 'Accra',
  'Grèce': 'Athènes',
  'Grenade': 'Saint-Georges',
  'Guatemala': 'Guatemala',
  'Guinée': 'Conakry',
  'Guinée-Bissau': 'Bissau',
  'Guinée équatoriale': 'Malabo',
  'Guyana': 'Georgetown',
  'Haïti': 'Port-au-Prince',
  'Honduras': 'Tegucigalpa',
  'Hongrie': 'Budapest',
  'Inde': 'New Delhi',
  'Indonésie': 'Jakarta',
  'Irak': 'Bagdad',
  'Iran': 'Téhéran',
  'Irlande': 'Dublin',
  'Islande': 'Reykjavik',
  'Israël': 'Jérusalem',
  'Italie': 'Rome',
  'Jamaïque': 'Kingston',
  'Japon': 'Tokyo',
  'Jordanie': 'Amman',
  'Kazakhstan': 'Astana',
  'Kenya': 'Nairobi',
  'Kirghizistan': 'Bichkek',
  'Kiribati': 'Tarawa',
  'Kosovo': 'Pristina',
  'Koweït': 'Koweït',
  'Laos': 'Vientiane',
  'Lesotho': 'Maseru',
  'Lettonie': 'Riga',
  'Liban': 'Beyrouth',
  'Liberia': 'Monrovia',
  'Libye': 'Tripoli',
  'Liechtenstein': 'Vaduz',
  'Lituanie': 'Vilnius',
  'Luxembourg': 'Luxembourg',
  'Macédoine du Nord': 'Skopje',
  'Madagascar': 'Antananarivo',
  'Malaisie': 'Kuala Lumpur',
  'Malawi': 'Lilongwe',
  'Maldives': 'Malé',
  'Mali': 'Bamako',
  'Malte': 'La Valette',
  'Maroc': 'Rabat',
  'Marshall': 'Majuro',
  'Maurice': 'Port-Louis',
  'Mauritanie': 'Nouakchott',
  'Mexique': 'Mexico',
  'Micronésie': 'Palikir',
  'Moldavie': 'Chisinau',
  'Monaco': 'Monaco',
  'Mongolie': 'Oulan-Bator',
  'Monténégro': 'Podgorica',
  'Mozambique': 'Maputo',
  'Namibie': 'Windhoek',
  'Nauru': 'Yaren',
  'Népal': 'Katmandou',
  'Nicaragua': 'Managua',
  'Niger': 'Niamey',
  'Nigeria': 'Abuja',
  'Norvège': 'Oslo',
  'Nouvelle-Zélande': 'Wellington',
  'Oman': 'Mascate',
  'Ouganda': 'Kampala',
  'Ouzbékistan': 'Tachkent',
  'Pakistan': 'Islamabad',
  'Palaos': 'Ngerulmud',
  'Palestine': 'Ramallah',
  'Panama': 'Panama',
  'Papouasie-Nouvelle-Guinée': 'Port Moresby',
  'Paraguay': 'Asuncion',
  'Pays-Bas': 'Amsterdam',
  'Pérou': 'Lima',
  'Philippines': 'Manille',
  'Pologne': 'Varsovie',
  'Portugal': 'Lisbonne',
  'Qatar': 'Doha',
  'République centrafricaine': 'Bangui',
  'République dominicaine': 'Saint-Domingue',
  'République démocratique du Congo': 'Kinshasa',
  'République tchèque': 'Prague',
  'Roumanie': 'Bucarest',
  'Royaume-Uni': 'Londres',
  'Russie': 'Moscou',
  'Rwanda': 'Kigali',
  'Saint-Christophe-et-Niévès': 'Basseterre',
  'Saint-Marin': 'Saint-Marin',
  'Saint-Vincent-et-les-Grenadines': 'Kingstown',
  'Sainte-Lucie': 'Castries',
  'Salomon': 'Honiara',
  'Salvador': 'San Salvador',
  'Samoa': 'Apia',
  'Sao Tomé-et-Principe': 'Sao Tomé',
  'Sénégal': 'Dakar',
  'Serbie': 'Belgrade',
  'Seychelles': 'Victoria',
  'Sierra Leone': 'Freetown',
  'Singapour': 'Singapour',
  'Slovaquie': 'Bratislava',
  'Slovénie': 'Ljubljana',
  'Somalie': 'Mogadiscio',
  'Soudan': 'Khartoum',
  'Soudan du Sud': 'Djouba',
  'Sri Lanka': 'Colombo',
  'Suède': 'Stockholm',
  'Suisse': 'Berne',
  'Suriname': 'Paramaribo',
  'Syrie': 'Damas',
  'Tadjikistan': 'Douchanbé',
  'Tanzanie': 'Dodoma',
  'Tchad': "N'Djaména",
  'Thaïlande': 'Bangkok',
  'Timor oriental': 'Dili',
  'Togo': 'Lomé',
  'Tonga': "Nuku'alofa",
  'Trinité-et-Tobago': "Port-d'Espagne",
  'Tunisie': 'Tunis',
  'Turkménistan': 'Achgabat',
  'Turquie': 'Ankara',
  'Tuvalu': 'Funafuti',
  'Ukraine': 'Kiev',
  'Uruguay': 'Montevideo',
  'Vanuatu': 'Port-Vila',
  'Vatican': 'Vatican',
  'Venezuela': 'Caracas',
  'Vietnam': 'Hanoï',
  'Yémen': 'Sanaa',
  'Zambie': 'Lusaka',
  'Zimbabwe': 'Harare',
};

// Listes de villes plus détaillées pour les pays les plus pertinents (gros marchés du padel).
const MAJOR_CITIES: Record<string, string[]> = {
  'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Bordeaux', 'Lille', 'Rennes'],
  'Maroc': ['Casablanca', 'Rabat', 'Marrakech', 'Fès', 'Tanger', 'Agadir', 'Meknès', 'Oujda'],
  'Algérie': ['Alger', 'Oran', 'Constantine', 'Annaba', 'Sétif'],
  'Espagne': ['Madrid', 'Barcelone', 'Valence', 'Séville', 'Saragosse', 'Malaga', 'Bilbao'],
  'Italie': ['Rome', 'Milan', 'Naples', 'Turin', 'Palerme', 'Bologne'],
  'Royaume-Uni': ['Londres', 'Manchester', 'Birmingham', 'Liverpool', 'Édimbourg', 'Glasgow'],
  'Belgique': ['Bruxelles', 'Anvers', 'Gand', 'Liège', 'Charleroi'],
  'Suisse': ['Zurich', 'Genève', 'Bâle', 'Berne', 'Lausanne'],
  'Allemagne': ['Berlin', 'Munich', 'Hambourg', 'Cologne', 'Francfort'],
  'Portugal': ['Lisbonne', 'Porto', 'Braga', 'Faro'],
  'États-Unis': ['New York', 'Los Angeles', 'Miami', 'Chicago', 'Houston', 'San Francisco'],
  'Canada': ['Montréal', 'Toronto', 'Vancouver', 'Ottawa', 'Québec'],
  'Égypte': ['Le Caire', 'Alexandrie', 'Gizeh'],
  'Émirats arabes unis': ['Dubaï', 'Abou Dabi', 'Charjah'],
  'Arabie saoudite': ['Riyad', 'Djeddah', 'La Mecque'],
  'Turquie': ['Istanbul', 'Ankara', 'Izmir', 'Antalya'],
  'Sénégal': ['Dakar', 'Thiès', 'Saint-Louis'],
  "Côte d'Ivoire": ['Abidjan', 'Yamoussoukro', 'Bouaké'],
  'Liban': ['Beyrouth', 'Tripoli', 'Saïda'],
  'Grèce': ['Athènes', 'Thessalonique'],
};

export function citiesForCountry(country: string): string[] {
  const cities = MAJOR_CITIES[country] ?? [CAPITALS[country]];
  return [...cities].sort((a, b) => a.localeCompare(b, 'fr'));
}
